#!/bin/bash

# 设置变量
XMRRIG_PATH="/opt/xmrig"
SYSTEMD_UNIT_FILE="/etc/systemd/system/xmrig.service"
USER="your_username"
GROUP="your_groupname"

# 从命令行参数中获取钱包地址
WALLET_ADDRESS="$1"

# 获取主机名
HOST_NAME=$(hostname)

# 下载xmrig
wget -P "$XMRRIG_PATH" https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-x64.tar.gz

# 解压
tar -zxvf "$XMRRIG_PATH/xmrig-6.21.0-linux-x64.tar.gz" -C "$XMRRIG_PATH"

# 创建Systemd Unit文件
cat <<EOF > "$SYSTEMD_UNIT_FILE"
[Unit]
Description=XMrig CryptoCurrency miner
After=network.target

[Service]
ExecStart=$XMRRIG_PATH/xmrig-6.21.0/xmrig -o zeph.kryptex.network:7777 -u "$WALLET_ADDRESS/$HOST_NAME" -k --coin zephyr -a rx/0
Restart=always

[Install]
WantedBy=multi-user.target
EOF

# 重新加载Systemd管理器配置
systemctl daemon-reload

# 启动服务
systemctl start xmrig

# 启用服务开机自启动
systemctl enable xmrig

apt update
apt install cpulimit
cpulimit -e xmrig -l 75 -b
sed -i -e '$acpulimit -e xmrig -l 75 -b\n' /etc/rc.local
echo -e '#!/bin/bash\nsudo cpulimit -e xmrig -l 75 -b' | sudo tee -a /etc/rc.local > /dev/null


# 显示服务状态
systemctl status xmrig
